# Generated by Django 3.1 on 2023-03-18 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20230315_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='repo_link',
            field=models.CharField(default='https://github.com/mfmyip/', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='technology',
            field=models.CharField(max_length=50),
        ),
    ]
